---
- name: Create isucon group
  become: yes
  become_user: root
  group:
    name: isucon
    gid: 1100
    state: present
    system: no

- name: Create isucon user
  become: yes
  become_user: root
  user:
    name: isucon
    uid: 1100
    group: isucon
    groups: "adm"
    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  become: yes
  become_user: root
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/99-isucon-user
    owner: root
    group: root
    mode: 0440

- name: Upgrade installed packages
  become: yes
  become_user: root
  apt:
    upgrade: safe
    update_cache: yes

- name: Install Package (Build)
  become: yes
  become_user: root
  apt:
    name:
    - libssl-dev
    - libreadline-dev
    - gcc
    - make
    - libffi-dev
    - zlib1g-dev
    - unzip
    - pkg-config
    - autoconf
    - automake
    - build-essential
    - nginx
    - libxml2-dev
    - libsqlite3-dev
    - libbz2-dev
    - libkrb5-dev
    - libcurl4-openssl-dev
    - libpng-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libc-client2007e-dev
    - libxslt1-dev
    - libonig-dev
    - libtidy-dev
    - libzip-dev
    - default-mysql-client
    - default-libmysqlclient-dev
    - python3-pip
