---
- name: install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /tmp/xbuild
    version: master

# in B4-training, we assume the use of Go language to run app

- name: Install Go 1.15.8
  become: yes
  become_user: isucon
  command: /tmp/xbuild/go-install 1.15.8 /home/isucon/local/go

- name: Add PATH for Go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go

# the script uses Node to run App

- name: Install Node v14.9.0
  become: yes
  become_user: isucon
  command: /tmp/xbuild/node-install v14.9.0 /home/isucon/local/node

- name: Add PATH for Node
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Node"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/node/bin:$PATH

# the script uses Python for App preparation

- name: Install python v3.8.5
  become: yes
  become_user: isucon
  command: /tmp/xbuild/python-install 3.8.5 /home/isucon/local/python

- name: Add PATH for python
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK python"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/python/bin:$PATH
