---
- name: Build Web Application Go
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isuumo/webapp/go/
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    make isuumo

- name: Copy Service file
  become: yes
  become_user: root
  copy:
    src: "/home/isucon/isuumo/conf/app/isuumo.go.service"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
    remote_src: yes
